In [8]:
import numpy as np
import sys

In [9]:
"""
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

https://numpy.org/doc/stable/reference/routines.array-creation.html

https://numpy.org/doc/stable/reference/routines.math.html

https://numpy.org/doc/stable/reference/routines.linalg.html
"""

'\nhttps://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html\n\nhttps://numpy.org/doc/stable/reference/routines.array-creation.html\n\nhttps://numpy.org/doc/stable/reference/routines.math.html\n\nhttps://numpy.org/doc/stable/reference/routines.linalg.html\n'

In [10]:
# Its all about arrays
"""
1-d, 2-d, 3-d arrays,   

Numpy uses fixed types ----> int32, 16, 8 --->which is further stored as binary internally
stored in contiguous memory location
-SIMD vector processing 
-effective cache utilization

--Maths, backbone of several frameworks, plotting, ML


Lists uses object types ---
which has object structure like this :- object value, type, reference count, size
all these fiels take some space for sure 

"""

#why to use ----> lists are slow 
#numpy uses fixed types while listes uses objects

'\n1-d, 2-d, 3-d arrays,   \n\nNumpy uses fixed types ----> int32, 16, 8 --->which is further stored as binary internally\nstored in contiguous memory location\n-SIMD vector processing \n-effective cache utilization\n\n--Maths, backbone of several frameworks, plotting, ML\n\n\nLists uses object types ---\nwhich has object structure like this :- object value, type, reference count, size\nall these fiels take some space for sure \n\n'

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0,8.0,7.0],[3.0,4.0,5.0]])
print(b)

[[9. 8. 7.]
 [3. 4. 5.]]


In [13]:
#dimesions
a.ndim

b.ndim

2

In [14]:
#shape
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [16]:
#get data type
#can be set explicitly set while creating array
a.dtype

dtype('int64')

In [17]:
c = np.array([2,4,6,8], dtype='int8')

In [18]:
c.dtype

dtype('int8')

In [19]:
#element size -- in bytes
a.itemsize

8

In [20]:
a.size

3

In [21]:
a.size * a.itemsize

24

In [22]:
a.nbytes

24

In [23]:
#----------------------Accessing / changing elements ------------------------#

In [24]:
a = np.array([
    [12,24,36,48,60],
    [13,26,39,52,65]
])

print(a)

[[12 24 36 48 60]
 [13 26 39 52 65]]


In [25]:
a[1,4]

65

In [26]:
a[1][-2]

52

In [27]:
#nth row, elements
a[0, :]

array([12, 24, 36, 48, 60])

In [28]:
#all rows, nth column
a[:, 2]

array([36, 39])

In [29]:
#[startIndex:endIndex:stepSize]

a[0, 1:4:2]
a[0, 1:-1:2]

array([24, 48])

In [30]:
a[1,2] = 99

In [31]:
a

array([[12, 24, 36, 48, 60],
       [13, 26, 99, 52, 65]])

In [32]:
a[:, 2] = 5
a

array([[12, 24,  5, 48, 60],
       [13, 26,  5, 52, 65]])

In [33]:
a[:, 2] = [36,39]
a

array([[12, 24, 36, 48, 60],
       [13, 26, 39, 52, 65]])

In [34]:
x = np.array(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]]
    ]
)

x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
##outside in

x[0,1,1]

4

In [36]:
x[:, 1, :]

array([[3, 4],
       [7, 8]])

In [37]:
x[:,0,0]

array([1, 5])

In [38]:
#------------------------------INITIALIZING ARRAY-------------------------------------#

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [43]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [44]:
#other number
np.full((2,2),3, dtype='float32')

array([[3., 3.],
       [3., 3.]], dtype=float32)

In [45]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [46]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [47]:
np.random.rand(4, 2, 3)

array([[[0.55366788, 0.37941857, 0.68080528],
        [0.32082325, 0.03236354, 0.15942882]],

       [[0.98329873, 0.10288017, 0.23979032],
        [0.8022971 , 0.40560512, 0.50492625]],

       [[0.07211138, 0.7459765 , 0.64171853],
        [0.38092242, 0.9122835 , 0.80181614]],

       [[0.03986104, 0.69922495, 0.08935648],
        [0.22994939, 0.27059144, 0.09640296]]])

In [48]:
np.random.random_sample(a.shape)

array([[0.26139936, 0.82409754, 0.7339819 , 0.23810395, 0.2909158 ],
       [0.0300996 , 0.01652611, 0.60004523, 0.24817907, 0.06452771]])

In [49]:
#number will be below 7 -- range is 7
np.random.randint(7, size=(3,3))

array([[2, 6, 2],
       [3, 2, 0],
       [1, 3, 6]])

In [50]:
np.random.randint(4, 8, size=(3,3))

array([[7, 5, 6],
       [4, 5, 6],
       [6, 6, 7]])

In [51]:
np.random.randint(-4, 8, size=(3,3))

array([[-4,  1, -3],
       [ 0,  2,  4],
       [-2,  0,  1]])

In [52]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [55]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
##copying arrays!!!!

a = np.array([1,2,3])
b = a
b[0] = 100
print(b)  #refers to a only
print(a)

[100   2   3]
[100   2   3]


In [58]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)  #refers to a only
print(a)

[100   2   3]
[1 2 3]


In [59]:
############## ------------------------ MATHEMATICS ---------------------- #################

In [60]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [61]:
a+2

array([3, 4, 5, 6])

In [62]:
a += 4
a

array([5, 6, 7, 8])

In [63]:
a-2

array([3, 4, 5, 6])

In [64]:
a*2

array([10, 12, 14, 16])

In [65]:
a/2

array([2.5, 3. , 3.5, 4. ])

In [66]:
b = np.array([1,0,1,0])

a+b

array([6, 6, 8, 8])

In [67]:
a ** 2

array([25, 36, 49, 64])

In [68]:
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [69]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [70]:
##### ---------- LINEAR ALGEBRA ----------- #############

In [71]:
f = np.ones((2,3))
print(f)

g = np.full((3,2), 2)
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [72]:
np.matmul(f,g)

array([[6., 6.],
       [6., 6.]])

In [73]:
a = np.identity(3)
a

#find determinant
np.linalg.det(a)

1.0

In [74]:
##trace, singular vector decomposition, eigenvalue, matrix norm, inverse ...

In [75]:
#######-------------STATISTICS-----------########

In [76]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.min(stats)

1

In [78]:
np.max(stats)

6

In [79]:
np.min(stats, axis=1)

array([1, 4])

In [80]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [81]:
np.sum(stats, axis=1)

array([ 6, 15])

In [82]:
np.sum(stats)

21

In [83]:
##############------------ Reorganizing Arrays -----------##############

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [85]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [86]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [87]:
#vertical stack

v1 = np.array([1,9,2,8])

v2 = np.array([4,5,6,7])

np.vstack([v1, v2])

np.vstack([v1, v2, v2, v2])

array([[1, 9, 2, 8],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [88]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [89]:
### Miscellaneous

In [90]:
filedata = np.genfromtxt('/content/drive/MyDrive/sample_data/numpy-data.txt', delimiter=',')

filedata = filedata.astype('int32')

filedata

array([[ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120],
       [ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130],
       [ 15,  30,  45,  60,  75,  90, 105, 120, 135, 150]], dtype=int32)

In [91]:
filedata > 50

array([[False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True]])

In [92]:
filedata[filedata > 50]

array([ 60,  72,  84,  96, 108, 120,  52,  65,  78,  91, 104, 117, 130,
        60,  75,  90, 105, 120, 135, 150], dtype=int32)

In [93]:
#index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [94]:
np.any(filedata > 50, axis=0)

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [95]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [98]:
######### Boolean Masking & Advanced Indexing

In [97]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False,  True,  True,  True,  True, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
        False]])

In [99]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True, False, False, False, False,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False,  True,  True,  True,
         True]])

In [101]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
v3 = np.array([11,12,13,14,15])
v4 = np.array([16,17,18,19,20])
v5 = np.array([21,22,23,24,25])
v6 = np.array([26,27,28,29,30])

arr = np.vstack([v1, v2, v3, v4, v5, v6])

In [102]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [103]:
arr[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [104]:
arr[
    [0,1,2,3],
    [1,2,3,4]
]

array([ 2,  8, 14, 20])

In [105]:
arr[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])